repository_type: pipeline
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nf-cmgg-preprocessing_logo_light.png
    - conf/test.config
    - conf/test_full.config
    - docs/images/nf-core-nf-cmgg-preprocessing_logo_light.png
    - docs/images/nf-core-nf-cmgg-preprocessing_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nf-cmgg-preprocessing_logo_light.png
    - docs/images/nf-core-nf-cmgg-preprocessing_logo_light.png
    - docs/images/nf-core-nf-cmgg-preprocessing_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .gitignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
