repository_type: pipeline

nf_core_version: 4.1.0

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-preprocessing_logo_light.png
    - docs/images/nf-core-preprocessing_logo_light.png
    - docs/images/nf-core-preprocessing_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .gitignore
    - assets/multiqc_config.yaml
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config: false
  files_exist:
    - CODE_OF_CONDUCT.md
    - docs/CONTRIBUTING.md
    - assets/nf-core-preprocessing_logo_light.png
    - docs/images/nf-core-preprocessing_logo_light.png
    - docs/images/nf-core-preprocessing_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  merge_markers:
    - bin/cmgg_genelists
    - .pixi/envs
  template_strings:
    - bin/cmgg_genelists
template:
  org: nf-cmgg
  name: preprocessing
  description: Demultiplexing, adapter trimming, alignment, and coverage calculation
    for NGS data.
  author: Matthias De Smet, Nicolas Vannieuwkerke and the CMGG IT Team
  version: 3.1.0dev
  force: true
  outdir: .
  skip_features:
    - fastqc
    - seqera_platform
    - gpu
    - citations
  is_nfcore: false
