lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - CITATIONS.md
    - assets/nf-core-preprocessing_logo_light.png
    - docs/images/nf-core-preprocessing_logo_light.png
    - docs/images/nf-core-preprocessing_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-preprocessing_logo_light.png
    - docs/images/nf-core-preprocessing_logo_light.png
    - docs/images/nf-core-preprocessing_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
  subworkflow_changes: false
  template_strings:
    - bin/cmgg_genelists
  merge_markers:
    - bin/cmgg_genelists
repository_type: pipeline
template:
  prefix: nf-cmgg
  skip: []
