%%metro title: nf-cmgg/preprocessing
%%metro style: nf-core
%%metro line: demux | Demultiplexing | #0000ff
%%metro line: alignment | Alignment and Postprocessing | #00ff00
%%metro line: qc | Quality control | #ff0000
%%metro file: BCL_IN | BCL
%%metro file: FASTQ_IN | FASTQ
%%metro line_order: span
%%metro compact_offsets: true

graph TD
    BCL_IN[]
    FASTQ_IN[]
    MULTIQC_LIBRARY
    MULTIQC_SAV

    subgraph Demultiplexing
        BCL_IN -->|demux| BCLCONVERT
        BCL_IN -->|qc| MULTIQC_SAV
        BCLCONVERT -->|qc| MULTIQC_SAV
    end

    subgraph FASTQ_QC
        FASTQ_IN -->|qc| FALCO
        FASTQ_IN -->|qc| FASTP
        BCLCONVERT -->|qc| FALCO
        BCLCONVERT -->|qc| FASTP
        FALCO -->|qc| MULTIQC_LIBRARY
        FASTP -->|qc| MULTIQC_LIBRARY
    end

    _CRAM

    subgraph Alignment_and_Postprocessing
        FASTQ_IN -->|alignment| ALIGN
        BCLCONVERT -->|alignment| ALIGN

        ALIGN -->|alignment| MARKDUP
        MARKDUP -->|alignment| _CRAM
    end

    _QC_COLLECT

    subgraph COVERAGE_QC
        _CRAM -->|qc| MOSDEPTH
        _CRAM -->|qc| SAMTOOLS_COV
        MOSDEPTH -->|qc| _QC_COLLECT
        SAMTOOLS_COV -->|qc| _QC_COLLECT
    end

    subgraph BAM_QC
        _CRAM -->|qc| SAMTOOLS_QC
        _CRAM -->|qc| PICARD
        SAMTOOLS_QC -->|qc| _QC_COLLECT
        PICARD -->|qc| _QC_COLLECT
    end

    _QC_COLLECT -->|qc| MULTIQC_LIBRARY
