%%metro title: nf-cmgg/preprocessing
%%metro logo: images/nf-cmgg-preprocessing_logo_dark.png
%%metro style: light

graph LR
%%metro entry: bcl_in | BCL
%%metro entry: fastq_in | FASTQ
%%metro file: fastq_in | FASTQ
%%metro file: bcl_in | BCL

%%metro line: main | Main | #4CAF50

%%metro line: demux | Demultiplexing | #4CAF50

%%metro line: align_bwamem1_bamsormadup_samtools_convert | Aligner: BWA MEM, Markdup: Biobambam Bamsormadup | #2196F3
%%metro line: align_bwamem2_bamsormadup_samtools_convert | Aligner: BWA MEM2, Markdup: Biobambam Bamsormadup | #2196F3
%%metro line: align_snapaligner_bamsormadup_samtools_convert | Aligner: Snap-aligner, Markdup: Biobambam Bamsormadup | #2196F3
%%metro line: align_star_bamsormadup_samtools_convert | Aligner: STAR, Markdup: Biobambam Bamsormadup | #2196F3
%%metro line: align_bowtie2_bamsormadup_samtools_convert | Aligner: Bowtie2, Markdup: Biobambam Bamsormadup | #2196F3
%%metro line: align_dragen_bamsormadup_samtools_convert | Aligner: Dragen, Markdup: Biobambam Bamsormadup | #2196F3
%%metro line: align_strobealigner_bamsormadup_samtools_convert | Aligner: Strobe-aligner, Markdup: Biobambam Bamsormadup | #2196F3

%%metro line: align_bwamem1_samtools_sormadup | Aligner: BWA MEM, Markdup: SAMtools Sormadup | #2196F3
%%metro line: align_bwamem2_samtools_sormadup | Aligner: BWA MEM2, Markdup: SAMtools Sormadup | #2196F3
%%metro line: align_snapaligner_samtools_sormadup | Aligner: Snap-aligner, Markdup: SAMtools Sormadup | #2196F3
%%metro line: align_star_samtools_sormadup | Aligner: STAR, Markdup: SAMtools Sormadup | #2196F3
%%metro line: align_bowtie2_samtools_sormadup | Aligner: Bowtie2, Markdup: SAMtools Sormadup | #2196F3
%%metro line: align_dragen_samtools_sormadup | Aligner: Dragen, Markdup: SAMtools Sormadup | #2196F3
%%metro line: align_strobealigner_samtools_sormadup | Aligner: Strobe-aligner, Markdup: SAMtools Sormadup | #2196F3

%%metro line: align_bwamem1_samtools_sort | Aligner: BWA MEM, Markdup: SAMtools Sort | #2196F3
%%metro line: align_bwamem2_samtools_sort | Aligner: BWA MEM2, Markdup: SAMtools Sort | #2196F3
%%metro line: align_snapaligner_samtools_sort | Aligner: Snap-aligner, Markdup: SAMtools Sort | #2196F3
%%metro line: align_star_samtools_sort | Aligner: STAR, Markdup: SAMtools Sort | #2196F3
%%metro line: align_bowtie2_samtools_sort | Aligner: Bowtie2, Markdup: SAMtools Sort | #2196F3
%%metro line: align_dragen_samtools_sort | Aligner: Dragen, Markdup: SAMtools Sort | #2196F3
%%metro line: align_strobealigner_samtools_sort | Aligner: Strobe-aligner, Markdup: SAMtools Sort | #2196F3

%%metro line: coverage | Coverage QC | #f38721ff

%%metro line: bam_qc_roi | BAM QC - ROI| #f32121ff
%%metro line: bam_qc_wgs | BAM QC - WGS| #f321e9ff

    subgraph demultiplexing [Basecalling & Demultiplexing]
        bcl_in[BCL]
        bclconvert[bcl-convert]
        multiqc_sav[MultiQC-SAV]
        demultiplex_out[Fastq]
        sav_out[SAV]

        bcl_in -->|demux| bclconvert
        bclconvert -->|demux| demultiplex_out
        bclconvert -->|demux| multiqc_sav
        multiqc_sav -->|demux| sav_out
    end

    subgraph genome_alignment [Genome Alignment]
        alignment_fastq_in[]
        bwamem[bwa mem]
        bwamem2[bwa mem2]
        snapaligner[snap-aligner]
        star[star]
        bowtie2[bowtie2]
        dragen[dragen]
        strobealigner[strobe-align]

        bamsormadup[biobambam bamsormadup]
        samtools_convert[samtools convert]
        samtools_sormadup[samtools sormadup]
        samtools_sort[samtools sort]

        cram_out[cram]

        alignment_fastq_in -->|align_bwamem1_bamsormadup_samtools_convert,align_bwamem1_samtools_sormadup,align_bwamem1_samtools_sort| bwamem
        alignment_fastq_in -->|align_bwamem2_bamsormadup_samtools_convert,align_bwamem2_samtools_sormadup,align_bwamem2_samtools_sort| bwamem2
        alignment_fastq_in -->|align_snapaligner_bamsormadup_samtools_convert,align_snapaligner_samtools_sormadup,align_snapaligner_samtools_sort| snapaligner
        alignment_fastq_in -->|align_star_bamsormadup_samtools_convert,align_star_samtools_sormadup,align_star_samtools_sort| star
        alignment_fastq_in -->|align_bowtie2_bamsormadup_samtools_convert,align_bowtie2_samtools_sormadup,align_bowtie2_samtools_sort| bowtie2
        alignment_fastq_in -->|align_dragen_bamsormadup_samtools_convert,align_dragen_samtools_sormadup,align_dragen_samtools_sort| dragen
        alignment_fastq_in -->|align_strobealigner_bamsormadup_samtools_convert,align_strobealigner_samtools_sormadup,align_strobealigner_samtools_sort| strobealigner

        bwamem -->|align_bwamem1_bamsormadup_samtools_convert| bamsormadup
        bwamem2 -->|align_bwamem2_bamsormadup_samtools_convert| bamsormadup
        snapaligner -->|align_snapaligner_bamsormadup_samtools_convert| bamsormadup
        star -->|align_star_bamsormadup_samtools_convert| bamsormadup
        bowtie2 -->|align_bowtie2_bamsormadup_samtools_convert| bamsormadup
        dragen -->|align_dragen_bamsormadup_samtools_convert| bamsormadup
        strobealigner -->|align_strobealigner_bamsormadup_samtools_convert| bamsormadup

        bamsormadup -->|align_bwamem1_bamsormadup_samtools_convert| samtools_convert
        bamsormadup -->|align_bwamem2_bamsormadup_samtools_convert| samtools_convert
        bamsormadup -->|align_snapaligner_bamsormadup_samtools_convert| samtools_convert
        bamsormadup -->|align_star_bamsormadup_samtools_convert| samtools_convert
        bamsormadup -->|align_bowtie2_bamsormadup_samtools_convert| samtools_convert
        bamsormadup -->|align_dragen_bamsormadup_samtools_convert| samtools_convert
        bamsormadup -->|align_strobealigner_bamsormadup_samtools_convert| samtools_convert

        bwamem -->|align_bwamem1_samtools_sormadup| samtools_sormadup
        bwamem2 -->|align_bwamem2_samtools_sormadup| samtools_sormadup
        snapaligner -->|align_snapaligner_samtools_sormadup| samtools_sormadup
        star -->|align_star_samtools_sormadup| samtools_sormadup
        bowtie2 -->|align_bowtie2_samtools_sormadup| samtools_sormadup
        dragen -->|align_dragen_samtools_sormadup| samtools_sormadup
        strobealigner -->|align_strobealigner_samtools_sormadup| samtools_sormadup

        bwamem -->|align_bwamem1_samtools_sort| samtools_sort
        bwamem2 -->|align_bwamem2_samtools_sort| samtools_sort
        snapaligner -->|align_snapaligner_samtools_sort| samtools_sort
        star -->|align_star_samtools_sort| samtools_sort
        bowtie2 -->|align_bowtie2_samtools_sort| samtools_sort
        dragen -->|align_dragen_samtools_sort| samtools_sort
        strobealigner -->|align_strobealigner_samtools_sort| samtools_sort

        samtools_convert -->|align_bwamem1_bamsormadup_samtools_convert| cram_out
        samtools_sormadup -->|align_bwamem1_samtools_sormadup| cram_out
        samtools_sort -->|align_bwamem1_samtools_sort| cram_out

        samtools_convert -->|align_bwamem2_bamsormadup_samtools_convert| cram_out
        samtools_sormadup -->|align_bwamem2_samtools_sormadup| cram_out
        samtools_sort -->|align_bwamem2_samtools_sort| cram_out

        samtools_convert -->|align_snapaligner_bamsormadup_samtools_convert| cram_out
        samtools_sormadup -->|align_snapaligner_samtools_sormadup| cram_out
        samtools_sort -->|align_snapaligner_samtools_sort| cram_out

        samtools_convert -->|align_star_bamsormadup_samtools_convert| cram_out
        samtools_sormadup -->|align_star_samtools_sormadup| cram_out
        samtools_sort -->|align_star_samtools_sort| cram_out

        samtools_convert -->|align_bowtie2_bamsormadup_samtools_convert| cram_out
        samtools_sormadup -->|align_bowtie2_samtools_sormadup| cram_out
        samtools_sort -->|align_bowtie2_samtools_sort| cram_out

        samtools_convert -->|align_dragen_bamsormadup_samtools_convert| cram_out
        samtools_sormadup -->|align_dragen_samtools_sormadup| cram_out
        samtools_sort -->|align_dragen_samtools_sort| cram_out

        samtools_convert -->|align_strobealigner_bamsormadup_samtools_convert| cram_out
        samtools_sormadup -->|align_strobealigner_samtools_sormadup| cram_out
        samtools_sort -->|align_strobealigner_samtools_sort| cram_out

    end

    subgraph coverage_qc [Coverage QC]
        coverage_qc_in[]
        mosdepth[mosdepth]
        samtools_coverage[samtools coverage]
        panelcoverage[Panel Coverage]
        coverage_qc_reports_out[Coverage Reports]

        coverage_qc_in -->|coverage| mosdepth
        coverage_qc_in -->|coverage| samtools_coverage
        coverage_qc_in -->|coverage| panelcoverage

        mosdepth -->|coverage| coverage_qc_reports_out
        samtools_coverage -->|coverage| coverage_qc_reports_out
        panelcoverage -->|coverage| coverage_qc_reports_out

    end

    subgraph bam_qc [BAM QC]
        bam_qc_in[]
        samtools_stats[samtools stats]
        samtools_flagstat[samtools flagstat]
        samtools_idxstats[samtools idxstats]
        picard_multiplemetrics[picard CollectMultipleMetrics]
        picard_hsmetrics[picard CollectHsMetrics]
        picard_wgsmetrics[picard CollectWgsMetrics]
        bam_qc_reports_out[QC Reports]

        bam_qc_in -->|bam_qc_roi,bam_qc_wgs| samtools_stats
        bam_qc_in -->|bam_qc_roi,bam_qc_wgs| samtools_flagstat
        bam_qc_in -->|bam_qc_roi,bam_qc_wgs| samtools_idxstats
        bam_qc_in -->|bam_qc_roi,bam_qc_wgs| picard_multiplemetrics
        bam_qc_in -->|bam_qc_roi| picard_hsmetrics
        bam_qc_in -->|bam_qc_wgs| picard_wgsmetrics

        samtools_stats -->|bam_qc_roi,bam_qc_wgs| bam_qc_reports_out
        samtools_flagstat -->|bam_qc_roi,bam_qc_wgs| bam_qc_reports_out
        samtools_idxstats -->|bam_qc_roi,bam_qc_wgs| bam_qc_reports_out
        picard_multiplemetrics -->|bam_qc_roi,bam_qc_wgs| bam_qc_reports_out
        picard_hsmetrics -->|bam_qc_roi| bam_qc_reports_out
        picard_wgsmetrics -->|bam_qc_wgs| bam_qc_reports_out
    end

    md5sum[md5sum]
    multiqc_main[Main MultiQC]
    multiqc_library[Library MultiQC]

    fastq_in -->|main| alignment_fastq_in
    demultiplex_out -->|main| alignment_fastq_in
    cram_out -->|main| coverage_qc_in
    cram_out -->|main| bam_qc_in
    cram_out -->|main| md5sum
    sav_out -->|main| multiqc_main
    coverage_qc_reports_out -->|main| multiqc_library
    bam_qc_reports_out -->|main| multiqc_library
